const products=[
 {id:'raspberry-cloud',category:'cakes',name:'Raspberry Cloud Cake',desc:'Vanilla bean cake, raspberry preserve, and whipped raspberry buttercream.',serves:'Serves 10 to 12',allergens:'Contains wheat, eggs, and milk.',price:68,flavours:['Vanilla raspberry','Chocolate raspberry']},
 {id:'lemon-sun',category:'cupcakes seasonal',name:'Little Lemon Suns',desc:'Lemon cake with bright curd centres and vanilla-lemon buttercream.',serves:'Box of 6',allergens:'Contains wheat, eggs, and milk.',price:24,flavours:['Lemon','Lemon raspberry']},
 {id:'midnight-cookies',category:'cookies',name:'Midnight Sea-Salt Cookies',desc:'Deep chocolate cookies with dark chocolate chunks and flaky salt.',serves:'Box of 8',allergens:'Contains wheat, eggs, milk, and soy.',price:22,flavours:['Classic','Espresso']},
 {id:'picnic-box',category:'boxes seasonal',name:'September Picnic Box',desc:'Two cupcakes, four cookies, two berry bars, and a little jar of lemon curd.',serves:'Serves 4 to 6',allergens:'Contains wheat, eggs, milk, and soy. May contain nuts.',price:42,flavours:['Baker’s selection']},
 {id:'chocolate-party',category:'cakes',name:'Chocolate Party Cake',desc:'Dark cocoa cake, milk-chocolate ganache, and soft vanilla buttercream.',serves:'Serves 12 to 16',allergens:'Contains wheat, eggs, milk, and soy.',price:78,flavours:['Chocolate','Mocha']},
 {id:'confetti-six',category:'cupcakes',name:'Confetti Six',desc:'Vanilla sprinkle cupcakes with swoops of vanilla buttercream.',serves:'Box of 6',allergens:'Contains wheat, eggs, milk, and soy.',price:22,flavours:['Vanilla','Chocolate']},
 {id:'jammy-hearts',category:'cookies',name:'Jammy Hearts',desc:'Tender butter cookies filled with raspberry jam.',serves:'Box of 10',allergens:'Contains wheat, eggs, and milk. May contain nuts.',price:25,flavours:['Raspberry','Apricot']},
 {id:'little-luxury',category:'boxes',name:'Little Luxury Box',desc:'A rotating assortment of small-batch cookies, bars, and truffles.',serves:'Serves 2 to 3',allergens:'Contains wheat, eggs, milk, and soy. May contain nuts.',price:32,flavours:['Baker’s selection']}
];
const bookedDates=['2026-09-19','2026-09-20','2026-09-26','2026-10-03','2026-10-10'];
let cart=JSON.parse(localStorage.getItem('wa-cart')||'[]');
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];

function nav(){const toggle=$('.menu-toggle'),links=$('.nav-links');if(toggle)toggle.addEventListener('click',()=>{const open=links.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});}
function renderProducts(){const root=$('#product-list');if(!root)return;root.innerHTML=products.map(p=>`<article class="product" data-category="${p.category}"><div class="product-swatch" aria-hidden="true"></div><div><h2>${p.name}</h2><p>${p.desc}</p><p class="meta">${p.serves}</p><p class="allergen"><strong>Allergens:</strong> ${p.allergens}</p><div class="product-actions"><span class="price">$${p.price}</span><button type="button" data-add="${p.id}">Choose</button></div></div></article>`).join('');$$('[data-add]').forEach(b=>b.addEventListener('click',()=>chooseProduct(b.dataset.add)));}
function filters(){$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;$$('.product').forEach(p=>p.hidden=f!=='all'&&!p.dataset.category.includes(f));}));}
function chooseProduct(id){const p=products.find(x=>x.id===id);let dialog=$('#order-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='order-dialog';dialog.className='order-dialog';document.body.append(dialog)}dialog.innerHTML=`<form method="dialog" class="order-panel"><div class="cart-top"><div><span class="script">Pack your box</span><h2>${p.name}</h2></div><button class="icon-button" value="cancel" aria-label="Close">×</button></div><p>${p.desc}</p><div class="field-grid"><div class="field"><label for="order-flavour">Flavour</label><select id="order-flavour">${p.flavours.map(f=>`<option>${f}</option>`).join('')}</select></div><div class="field"><label for="order-quantity">Quantity</label><input id="order-quantity" type="number" min="1" max="12" value="1" required></div><div class="field"><label for="order-date">Pickup date</label><input id="order-date" type="date" min="${new Date().toISOString().split('T')[0]}" required><p class="help" id="order-date-help">Select a Friday or Saturday pickup date.</p></div></div><button class="button" id="add-confirm" value="default">Add to bakery box</button></form>`;const date=$('#order-date',dialog),help=$('#order-date-help',dialog);date.addEventListener('change',()=>{const unavailable=bookedDates.includes(date.value);help.textContent=unavailable?'That date is fully booked. Please choose another.':'That date is currently available.';help.style.color=unavailable?'var(--raspberry)':'var(--green)';date.setCustomValidity(unavailable?'That date is fully booked.':'')});dialog.addEventListener('close',()=>{if(dialog.returnValue!=='default')return;if(!date.value||!date.checkValidity()){date.reportValidity();return;}cart.push({...p,flavour:$('#order-flavour',dialog).value,quantity:Number($('#order-quantity',dialog).value),date:date.value});saveCart();openCart()},{once:true});dialog.showModal();}
function saveCart(){localStorage.setItem('wa-cart',JSON.stringify(cart));updateCart();}
function updateCart(){const count=cart.reduce((n,i)=>n+i.quantity,0);$$('[data-cart-count]').forEach(x=>x.textContent=count);const content=$('#cart-content');if(!content)return;if(!cart.length){content.innerHTML='<div class="cart-empty"><p class="script">The box is empty</p><p>Choose something from the menu. A small tragedy, easily corrected.</p></div>';return;}const total=cart.reduce((n,i)=>n+i.price*i.quantity,0);content.innerHTML=cart.map((i,n)=>`<div class="cart-item"><strong>${i.name}</strong><br><span>${i.flavour} · Qty ${i.quantity}</span><br><span>Pickup ${i.date}</span><button type="button" class="filter" data-remove="${n}">Remove</button></div>`).join('')+`<p class="cart-total"><span>Total</span><span>$${total.toFixed(2)}</span></p><div class="mock-notice"><strong>Prototype checkout</strong><br>No payment will be processed. A live site would hand this order to Stripe Checkout or Square.</div><button class="button" type="button" id="review-order">Review mock order</button>`;$$('[data-remove]').forEach(b=>b.addEventListener('click',()=>{cart.splice(Number(b.dataset.remove),1);saveCart()}));$('#review-order')?.addEventListener('click',()=>toast('Order reviewed. Payment remains safely fictional.'));}
function openCart(){const d=$('#cart-drawer');d?.classList.add('open');d?.setAttribute('aria-hidden','false');$('#cart-close')?.focus();}
function cartControls(){$$('.cart-button').forEach(b=>b.addEventListener('click',openCart));$('#cart-close')?.addEventListener('click',()=>{$('#cart-drawer').classList.remove('open');$('#cart-drawer').setAttribute('aria-hidden','true')});updateCart();}
function toast(message){const t=$('#toast');if(!t)return;t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}
function dateCheck(){const input=$('#pickup-date'),status=$('#date-status');if(!input||!status)return;input.min=new Date().toISOString().split('T')[0];input.addEventListener('change',()=>{const unavailable=bookedDates.includes(input.value);status.textContent=unavailable?'That date is fully booked. Try another pickup day.':'This date is currently available for a request.';status.classList.toggle('booked',unavailable);input.setCustomValidity(unavailable?'This date is fully booked.':'');});}
function forms(){$$('form[data-prototype]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const result=$('.form-result',form);if(result){result.hidden=false;result.focus()}form.reset();toast('Request prepared. Nothing was sent from this portfolio prototype.')}));}
nav();renderProducts();filters();cartControls();dateCheck();forms();
